// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/common/common.proto

package common // import "github.com/879229629/demo/common/protobuf/common"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Resp struct {
	ErrorCode            int64    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg             int64    `protobuf:"varint,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1141f1985e08062b, []int{0}
}
func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (dst *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(dst, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Resp) GetErrorMsg() int64 {
	if m != nil {
		return m.ErrorMsg
	}
	return 0
}

func init() {
	proto.RegisterType((*Resp)(nil), "common.Resp")
}

func init() {
	proto.RegisterFile("protocol/common/common.proto", fileDescriptor_common_1141f1985e08062b)
}

var fileDescriptor_common_1141f1985e08062b = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x52, 0x7a, 0x60, 0x61,
	0x21, 0x36, 0x08, 0x4f, 0xc9, 0x81, 0x8b, 0x25, 0x28, 0xb5, 0xb8, 0x40, 0x48, 0x86, 0x8b, 0xd3,
	0xb5, 0xa8, 0x28, 0xbf, 0xc8, 0x39, 0x3f, 0x25, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x08,
	0x21, 0x20, 0x24, 0xc5, 0xc5, 0x01, 0xe6, 0xf8, 0x16, 0xa7, 0x4b, 0x30, 0x81, 0x25, 0xe1, 0x7c,
	0x27, 0xa3, 0x28, 0x83, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x0b,
	0x73, 0x4b, 0x23, 0x23, 0x4b, 0x33, 0x23, 0x4b, 0xfd, 0x94, 0xd4, 0xdc, 0x7c, 0x98, 0xd5, 0x60,
	0x3b, 0x93, 0x4a, 0xd3, 0xa0, 0xfc, 0x24, 0x36, 0xb0, 0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x3e, 0xe3, 0xd8, 0x1a, 0xa4, 0x00, 0x00, 0x00,
}
