// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/order/order.proto

package order // import "github.com/879229629/demo/common/protobuf/order"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/879229629/demo/common/protobuf/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order struct {
	OrderId              int64        `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Resp                 *common.Resp `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_ec6bbbe72db0f091, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Order) GetResp() *common.Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "order.Order")
}

func init() { proto.RegisterFile("protocol/order/order.proto", fileDescriptor_order_ec6bbbe72db0f091) }

var fileDescriptor_order_ec6bbbe72db0f091 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0xcf, 0x2f, 0x4a, 0x49, 0x2d, 0x82, 0x90, 0x7a, 0x60, 0x41, 0x21,
	0x56, 0x30, 0x47, 0x4a, 0x06, 0xae, 0x24, 0x39, 0x3f, 0x37, 0x37, 0x3f, 0x0f, 0x4a, 0x41, 0x14,
	0x29, 0x39, 0x73, 0xb1, 0xfa, 0x83, 0x94, 0x09, 0x49, 0x70, 0xb1, 0x83, 0x19, 0x9e, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x30, 0xae, 0x90, 0x02, 0x17, 0x4b, 0x51, 0x6a, 0x71, 0x81,
	0x04, 0x93, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0x8f, 0x1e, 0x54, 0x7f, 0x50, 0x6a, 0x71, 0x41, 0x10,
	0x58, 0xc6, 0xc9, 0x30, 0x4a, 0x3f, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x09, 0x24, 0xa7, 0x6f, 0x61,
	0x6e, 0x69, 0x64, 0x64, 0x69, 0x66, 0x64, 0xa9, 0x9f, 0x92, 0x9a, 0x9b, 0x0f, 0xb3, 0x15, 0x6c,
	0x5d, 0x52, 0x69, 0x1a, 0xc4, 0x89, 0x49, 0x6c, 0x60, 0xbe, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x98, 0x01, 0xcb, 0xf9, 0xc1, 0x00, 0x00, 0x00,
}
